# Generated by Django 3.2.8 on 2021-10-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('whodonit', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Solves',
            },
        ),
        migrations.AlterModelOptions(
            name='characters',
            options={'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='clues',
            options={'verbose_name_plural': 'Clues'},
        ),
    ]
