# Generated by Django 3.2.8 on 2021-10-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211026_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='relation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
